name: 'Stale issue handler'
on:
  # workflow_dispatch:
  schedule:
    # specifying cron to run build at 4.00pm daily
    - cron: '0 4 * * *'

jobs:
  stale_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/stale@main
        id: stale
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 1 day with no activity. Remove stale label or comment or this will be closed in 2 days'
          days-before-stale: 1

          # close-issue-reason: 'User has been notified of stale issue and issue requires to be closed after 2 days'
          days-before-close: 2

          exempt-issue-labels: 'blocked,must,should,keep'

      - name: Print stale outputs 
        run: |
          echo ${{ join(steps.stale.outputs.*, ',') }}
          echo "Job Status ${{job.status}}"
          
  print_output_job:
    runs-on: ubuntu-latest
    needs: [stale_job]
    steps:        
      - name: Print OS-name 
        run: |
          cat /etc/os-release
      - name: List all files in the directory
        run: |
          ls ${{github.workspace}}
